# Generated by Django 6.0.5 on 2026-05-27 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('role', models.CharField(help_text='Ex: Manicure, Designer de Sobrancelhas', max_length=100, verbose_name='Especialidade')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='professionals/', verbose_name='Foto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlockedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_date', models.DateField(verbose_name='Data do Bloqueio')),
                ('start_time', models.TimeField(verbose_name='Horário de Início')),
                ('end_time', models.TimeField(verbose_name='Horário de Fim')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_slots', to='accounts.professional')),
            ],
            options={
                'verbose_name': 'Horário Bloqueado',
                'verbose_name_plural': 'Horários Bloqueados',
                'ordering': ['block_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('start_time', models.TimeField(verbose_name='Horário de Início')),
                ('end_time', models.TimeField(verbose_name='Horário de Fim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='accounts.professional')),
            ],
            options={
                'verbose_name': 'Horário de Trabalho',
                'verbose_name_plural': 'Horários de Trabalho',
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('professional', 'weekday')},
            },
        ),
    ]
