# Generated by Django 5.2.14 on 2026-05-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedslot',
            name='block_date',
            field=models.DateField(db_index=True, verbose_name='Data do Bloqueio'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], db_index=True, verbose_name='Dia da Semana'),
        ),
    ]
