# Generated by Django 5.2.14 on 2026-06-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_blockedslot_block_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='phone',
            field=models.CharField(blank=True, help_text='Apenas números com DDD, ex: 41988477213', max_length=20, verbose_name='WhatsApp/Telefone'),
        ),
    ]
