# Generated by Django 5.2.14 on 2026-06-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_professional_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='google_calendar_email',
            field=models.EmailField(blank=True, help_text='E-mail Gmail da profissional para receber convites de agendamento na agenda do Google', max_length=254, verbose_name='Gmail (Google Agenda)'),
        ),
    ]
