# Generated by Django 6.0.5 on 2026-05-27 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Nome da Cliente')),
                ('client_email', models.EmailField(max_length=254, verbose_name='E-mail da Cliente')),
                ('client_phone', models.CharField(max_length=20, verbose_name='WhatsApp da Cliente')),
                ('appointment_date', models.DateField(verbose_name='Data do Agendamento')),
                ('appointment_time', models.TimeField(verbose_name='Horário do Agendamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='confirmed', max_length=20, verbose_name='Status')),
                ('cancel_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de Cancelamento')),
                ('cancel_token_expires', models.DateTimeField(blank=True, null=True, verbose_name='Expiração do Token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='accounts.professional')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('confirmation', 'Confirmação'), ('reminder_24h', 'Lembrete 24h'), ('cancellation', 'Cancelamento')], max_length=20, verbose_name='Tipo de E-mail')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Destinatário')),
                ('sent_success', models.BooleanField(default=True, verbose_name='Enviado com Sucesso')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='booking.appointment')),
            ],
            options={
                'verbose_name': 'Log de E-mail',
                'verbose_name_plural': 'Logs de E-mail',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.professional')),
            ],
            options={
                'verbose_name': 'Serviço por Profissional',
                'verbose_name_plural': 'Serviços por Profissional',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Duração (minutos)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, max_length=10, verbose_name='Preço (R$)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professionals', models.ManyToManyField(related_name='services', through='booking.ProfessionalService', to='accounts.professional')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='professionalservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='booking.service'),
        ),
        migrations.AlterUniqueTogether(
            name='professionalservice',
            unique_together={('professional', 'service')},
        ),
    ]
